### ISSUE TITLE
Why 2 queries

### ISSUE THREAD

**Issue by vlad-ghita** [symphonists/url_router#1]
Hmm, this looks odd ...

Why are there [2 queries](https://github.com/symphonists/url_router/blob/master/extension.driver.php#L18-26) performed on installation?

**Comment by designermonkey** [comment]
Well, spotted! I was playing with automatically uninstallng the old router by renaming the table and then removing the extension rows in the relevant extension tables to save the user from having to re input all the data from the old router, but couldn't get it to work properly.

Thanks for finding this! It was bugging me as I was sure I'd removed it ;)

This will be why it breaks the old router then!

**Comment by vlad-ghita** [comment]
> This will be why it breaks the old router then!

Regarding your last commit, perhaps you would like to review the [disclaimer notice](http://symphony-cms.com/discuss/thread/37320/2/#position-36) on the forum.

**Comment by designermonkey** [comment]
done ;)
