### ISSUE TITLE
Routing params to homepage breaks 404

### ISSUE THREAD

**Issue by designermonkey** [symphonists/url_router#13]
When doing it's wonderful thang of routing anything that doesn't match a 'page' to the root page's params, 404 pages are broken.

Is there any way we can check the root pages params and redirect to 404 if they don't exist? Should this be something that is done in the main datasource for the root page, using it's 404 method? Should we therefore be telling people to make sure they do this?

Thoughts from @alpacaa @tonyarnold and @nils-werner appreciated.

**Comment by creativedutchmen** [comment]
@designermonkey I've one exactly that in the `root page param` extension: tell people not to forget the 404 datasource. From memory it should return a 404 if the root page does not have enough params to build the url, and if it doesn't I think it's a bug.

**Comment by designermonkey** [comment]
Yeah, it was me not using a datasource with 404.
