### ISSUE TITLE
Server root vs. Symphony root

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/url_router#15]
I'd like to redirect from a page `team` to a page `anmeldung` as soon as `team` doesn't have any additional URL parameters set. I got the router to match the needed `from` path using `/team?\/$/` but I'm running into a problem with the redirection: it doesn't redirect based on Symphony's document root but based on the server root (I tried either `anmeldung` or `/anmeldung/` without success). So when my `from` URL is `http://localhost/example.com/team/` I get redirected to `http://localhost/anmeldung/` – but I'd like to end at `http://localhost/example.com/anmeldung/`.

I'd expect this extension to always redirect based on Symphony's document root and not the server root.

**Comment by designermonkey** [comment]
What version of Symphony and the extension are you using?

**Comment by nilshoerrmann** [comment]
You were to fast: I was just looking this up :)

The version number is displayed as `2`, so I guess it's `2.0`.
I'm using Symphony 2.3.

**Comment by designermonkey** [comment]
I can see where this may be happening. The `context` passed into a delegate function for `FrontendPrePageResolve` has a  `page` which is replaced by the routed url.

I'm sorry that I havent got something set up that I can test this on, does the `$context['page']` before line `191` contain the full url including the scheme? If so, then I can fix this very easily. If not, I'll have to think why it's missing the `$root` when it redirects.

**Comment by nilshoerrmann** [comment]
`$context['page']` is set to `/team/` – no root nor scheme included.

**Comment by nilshoerrmann** [comment]
In this case, shouldn't lines 204 and 208 just include the root?

**Comment by designermonkey** [comment]
I was thinking it was more an issue outside of URL ROuter, but I think you're right after all!

Well Spotted Nils. I shall sort this now.

**Comment by designermonkey** [comment]
Nils, can you test this for me? Cheers.

**Comment by nilshoerrmann** [comment]
Works as expected. Thanks, John!
