### ISSUE TITLE
Simplified notation

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/url_router#16]
When creating new routes, the help text for simplified notations displays like this:

> Simplified: page-name/$user/projects/$project

After saving it looks like this:

> Simplified: page-name/:user/projects/:project

Only one can be right. Which?

**Comment by nilshoerrmann** [comment]
There is another inconsistency:

Why does the `from` part exclude a slash at the beginning while the `to` part seems to require one?
( `Simplified: page-name/:user/projects/:project` vs. `Simplified: /new-page-name/:user/:project`)

**Comment by DavidOliver** [comment]
I'm also interested in `$user` versus `:user`. The latter seems to be what people at the forum use(d).

**Comment by DavidOliver** [comment]
@jensscherbl is using `$`, so maybe they both work. Would be good to know what the recommended way is, though.

**Comment by jensscherbl** [comment]
As far as I remember, I tried `:user` notation first and it didn't work (consistently).

Since we're using `$user`-notation everywhere else in Symphony (params), I guess the `:user`-notation is just wrong in the UI?
