### ISSUE TITLE
Extension gets activated but no Nav-Pages or Settings appear

### ISSUE THREAD

**Issue by animaux** [symphonists/url_router#17]
Copied from Symphony CMS Forum:

It might be messed up permissions on my particular Symphony 2.3 installation here, but I can’t for the life of me get this extension (2.0.1, though readme says 1.3) working. I tried on two different 2.3 installations, the activation works fine, but I get no options in my preferences and no other options in any navgroups either. Am I missing something very obvious again? :)

**Comment by designermonkey** [comment]
`2.3` changed the way navigation groups are added, and I missed it.

Will fix asap.

**Comment by animaux** [comment]
Brill!

**Comment by designermonkey** [comment]
Looking into this, the extension works fine on my builds.

The new group is available under Blueprints > URL Routes. Is that where you were looking?

**Comment by animaux** [comment]
Nope, it’s not there. Maybe it’s somehow related to both of my 2.3 installations having been upgraded from 2.2.x?

**Comment by nils-werner** [comment]
Is your installation set to english?

If not you can try and wrap `'Blueprints'` in [extensions.driver.php:24](https://github.com/symphonists/url_router/blob/master/extension.driver.php#L24) in localization brackets: `__('Blueprints')`

**Comment by animaux** [comment]
It is not, setting it to english makes it work. And of course the brackets too. Should I fork and send a pull request? I Guess it’s faster if you add this, Nils?

Thanks!

**Comment by nils-werner** [comment]
@designermonkey Can you do this while you're merging PR #14?

**Comment by nils-werner** [comment]
I've fixed this in the `master` branch.

**Comment by animaux** [comment]
brilliant, thanks!
