### ISSUE TITLE
Implement rails like routing

### ISSUE THREAD

**Issue by alpacaaa** [symphonists/url_router#2]
Very good extension, just having some problems with regexp.

Would be very cool if you could define routes as rails does. Something like this:

```
user/:name/comments => user/comments/:name
user/:name/comments/:comment-id => user/comments/:name/:comment-id
```

Of course regexp are a lot more flexible, but I think this is a very good solution for those who don't need that level of control.
Don't know how difficult is implementing this idea, but would be very cool ;)

**Comment by nils-werner** [comment]
How about introducing several predefined parameter classes like "string", "number" and replacing them by regular expressions on the fly?

**Comment by alpacaaa** [comment]
@nils looks like a good idea!

I'll probably get to this issue very soon, just posting [this gist](https://gist.github.com/1241844) for future reference (seems to be what we need).

**Comment by alpacaaa** [comment]
Here it is!

https://github.com/alpacaaa/url_router/tree/rails-routing

What do ya think? :)

**Comment by bauhouse** [comment]
I like it! Much simpler. I wonder if it would be possible to set a preference for the routing method, to use either regex or rails style routing.
