### ISSUE TITLE
Having trouble routing urls with the force re-route checkbox removed

### ISSUE THREAD

**Issue by jude86-7** [symphonists/url_router#22]
The page I am trying to route exists and without the check box 'force re-route even if page exists' it doesn't seem to work for me. Am I doing something wrong?

I have two pages;

projects (shows a list of projects)
projects/projects-single (shows project detail and accepts the $project-title url parameter)

Currently the route for the individual project is 

from
/\/projects\/(.+)\//

to
/projects/projects-single/$1/

this works with older versions of the router but not 3.1 - if any one can point me in the right direction I would be grateful.

Many thanks

**Comment by twiro** [comment]
Hey @jude86-7 ... just in case you didn't get this fixed until now (I hope you did!) - I just played around with **url_router** for the very first time and tested a few scenarios including the one you're reporting here.

I'm using version 3.1 in Symphony 2.6.X and everything works as expected if I write the regular expression this way:

**From:**

    /\/projects\/(.+\/)/

**To:**

    /projects/projects-single/$1/

So the following example will be routed as expected and actually call your `projects-single`-page passing a `project-title`-parameter:

**URL:**

    http://domain.com/projects/project-title/?debug

**Debug Data:**

```
<data>
    <params>
        <root-page>projects</root-page>
        <current-page>projects-single</current-page>
        <current-path>/projects/project-handle</current-path>
        <parent-path>/projects</parent-path>
        <param>project-title</param>
    </params>
</data>
```

**Comment by jude86-7** [comment]
Hey @twiro thank you so much for coming back to me on this. I did get the issue sorted, my apologies I forgot I had even written this post! Otherwise I would have marked it as resolved. 

Using the regular expression the way you suggest is the way I got it working and I'm sure this will come in useful for others in the future.

Thanks again for taking the time to help!
