### ISSUE TITLE
Broken on 2.6.0?

### ISSUE THREAD

**Issue by munki-boy** [symphonists/url_router#23]
Symphony Warning: preg_match(): Unknown modifier 'h'

An error occurred in D:\wamp\www\pb\extensions\url_router\extension.driver.php around line 102

```
97
98             $return = array();
99
100             foreach($routes as $route)
101             {
102                 if(preg_match($route['from'], $path, $matches) == 1)
103                 {
104                     $route['routed'] = preg_replace($route['from'], $route['to'], $path);
105
106                     $route['original'] = $path; 
```

**Comment by munki-boy** [comment]
If the extension is enabled and any route is added.  Visiting any site pages (even those not related to the added route) produces the error.

**Comment by nitriques** [comment]
Where's the 'h' coming from ?

**Comment by munki-boy** [comment]
I don't know, something to do with regex? 

It's a simple route like "/fr/home To /fr/acceuil"

But the error only happens when the path has a second part. So "/fr/" is ok, but "/fr/whatever" is broken.

**Comment by munki-boy** [comment]
is it like this?

[http://stackoverflow.com/questions/22684220/preg-match-unknown-modifier-h-in-php](http://stackoverflow.com/questions/22684220/preg-match-unknown-modifier-h-in-php)

**Comment by munki-boy** [comment]
Yep the 'h' is the start of the word 'home'

**Comment by munki-boy** [comment]
Working now, was my fault trying to write a nested page's path into the box.

**Comment by nitriques** [comment]
Oh! Great then!
