### ISSUE TITLE
MySQL error: Column count doesn't match value count

### ISSUE THREAD

**Issue by froschdesign** [symphonists/url_router#3]
Hello Symphonists,
I get an error when I try to save my route definitions.
### Example to reproduce the problem

First route: "Force re-route if page exists" is checked
Second route: "Force re-route if page exists" is not checked

The generated query:

```
INSERT INTO
    `sym_url_router` (`type`, `from`, `to`, `http301`)
VALUES
    ('route', '/\/foo\/(.+\/)/', '/foo/$1', 'yes'),
    ('route', '/\/foo\/(.+\/)/', '/foo/$1')
```

Error message:

> Error : Column count doesn't match value count at row 2

(MySQL version is 5.1.32)

**Comment by bauhouse** [comment]
I seem to have come across the same issue. I clicked the "Force re-route if page exists" checkbox and saving the preferences returned the same error. Except, in my case, all routes were deleted.
