### ISSUE TITLE
Only the first route works

### ISSUE THREAD

**Issue by bauhouse** [symphonists/url_router#4]
When setting multiple routes, only the first route works as expected. All other routes are ignored.

I tracked down the problem to the `break` function. The `break` should end the loop only if a match is found. So, just move the `break` inside the if statement group.

```
foreach($routes as $route)
{
    if(preg_match($route['from'], $path, $matches) == 1)
    {
        $route['routed'] = preg_replace($route['from'], $route['to'], $path);

        $route['original'] = $path;

        $return = $route;

        break;
    }
}
```

**Comment by designermonkey** [comment]
Good spot, although it never broke my installs before.

Are you passing a route to another route?

**Comment by bauhouse** [comment]
I don't think I'm passing a route to another route. Here's my list of routes:
- From `/\/(\d{4})\/overview/` to `/overview/$1/`
- From `/\/(\d{4})\/sponsorship/` to `/sponsorship/$1/`
- From `/\/(\d{4})\/schedules/` to `/schedules/$1/`
- From `/\/(\d{4})\/speakers/` to `/speakers/$1/`
- From `/\/(\d{4})\/register/` to `/register/$1/`
- From `/\/(\d{4})\/contact-us/` to `/contact-us/$1/`
- From `/\/(\d{4})\/page-not-found/` to `/page-not-found/$1/`

Although, I'm now using [Marco's fork](https://github.com/alpacaaa/url_router/tree/rails-routing), using Rails style routing:
- From `/:year/overview/` to `/overview/:year/`
- From `/:year/sponsorship/` to `/sponsorship/:year/`
- From `/:year/schedules/` to `/schedules/:year/`
- From `/:year/speakers/` to `/speakers/:year/`
- From `/:year/register/` to `/register/:year/`
- From `/:year/contact-us/` to `/contact-us/:year/`
- From `/:year/page-not-found/` to `/page-not-found/:year/`
