### ISSUE TITLE
"Too Many Redirects" error using a 'redirect' instead of a 'route'

### ISSUE THREAD

**Issue by davidhund** [symphonists/url_router#7]
Using Symphony 2.2.3 and URL_Router 1.2.

I've added a Route and a Redirect. Redirects consistently throw a browser error "310 Too many redirects". Changing the same regEx etc. to a 'Route' works fine.

**Comment by nils-werner** [comment]
Can you tell us what exact rule you're using?

**Comment by davidhund** [comment]
Yes sir, I can: 

![Screenshot](https://img.skitch.com/20111114-mm7adp8kky1nynjnp8bjgejmmy.jpg)

**Comment by designermonkey** [comment]
Good spot!
