### ISSUE TITLE
Target-URL with querystring results in Too Many Redirects error

### ISSUE THREAD

**Issue by davidhund** [symphonists/url_router#8]
(Symphony 2.2.5 and Url Router 1.2)

As described on the [Forum](http://symphony-cms.com/discuss/thread/37320/4/#position-66)

The URL Router adds a trailing slash ("/") to a route when there's no trailing slash in the To-URL. 
Example: I redirect `/\/abonneer/` to `http://foo.bar.list-manage.com/subscribe?u=123abc` (note the querystring and lack of trailing slash)

My destination url becomes http://foo.bar.list-manage.com/subscribe?u=123abc/ and fails on the trailing slash ("Too many redirects" error).

The slash seems always added in extension.driver.php:123 which (in my case) is unwanted since there's a querystring.

**Comment by designermonkey** [comment]
David, perfectly understandable that this would be annoying. I'll get on it ASAP.

**Comment by designermonkey** [comment]
Looking into this, the line in question wouldn't be adding a trailing slash to your redirect as it would only be called if you were using rails type routing.

Are you sure it's not the Symphony htaccess rules that are adding the slash?

I will continue to look at this when I've got some real time.

**Comment by davidhund** [comment]
John, thanks. 

Just a quick reply (have not looked into it much further) but I don't think it's Symphony's .htaccess since the TO URL is on a different domain, right? So it does not go through Symphony's .htaccess first but go straight to the other domain, I believe…

**Comment by designermonkey** [comment]
This is the longest it's ever taken me to get back to an issue. That's not very good.

I've just come across a problem myself with using querystrings and it made me stumble over this again. The reason it won't work properly is that we haven't ever considered this being able to redirect outside of Symphony, i.e. to another website, so it will treat all URLs as internal.

To fix my issue, I need to handle querystrings in the redirected URL, to change them into GET params. I think I can check whether `http` exists in the `to` field and do nothing if it does.

I just need consensus that we should be using this extension to redirect to external URLs or not first, @nils-werner, @alpacaaa, what do you guys think?

**Comment by designermonkey** [comment]
The integration branch has the required changes.

I must say though that at no point in this code is a `/` appended to the URL, internal or external so @davidhund if this problem persists, it must be the target site.
