### ISSUE TITLE
Help Text is Switched Around

### ISSUE THREAD

**Issue by TheJester12** [symphonists/url_router#9]
The help text for the new rails style routing is switched around - making this extension pretty confusing for newcomers. See thread: http://symphony-cms.com/discuss/thread/37320/4/#position-64

**Comment by designermonkey** [comment]
Just want to apologize that I haven't picked this up. Github seems to be not sending me notifications about these issues.

I'll look into this for you shortly...

**Comment by brendo** [comment]
This is already sorted ;)
